services:
  app:
    image: "ghcr.io/ma-zal/json-document-storage:latest"
    container_name: json-document-storage
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - json-document-storage
    environment:
      # DB configuration
      POSTGRES_HOST: postgres
      POSTGRES_USER: jsondocumentstorage
      POSTGRES_DB: jsondocumentstorage
    build:
      context: .
      args:
        http_proxy: ${http_proxy}   # variable passed from host shell
        https_proxy: ${https_proxy} # variable passed from host shell
        no_proxy: ${no_proxy}       # variable passed from host shell

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    networks:
      - json-document-storage
    environment:
      POSTGRES_USER: jsondocumentstorage
      POSTGRES_DB: jsondocumentstorage
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

networks:
  json-document-storage:
    name: json-document-storage_default
